"""Snapshot v1 — the canonical artifact of a fleet audit.

Phase 2's `fleet diff`, future `fleet report` / `fleet export`, and any
external dashboard all read Snapshots. The contract is versioned; see
`docs/superpowers/specs/2026-06-02-configguard-fleet-mode-design.md`.

The Snapshot is **self-contained**: per-device `findings` are embedded,
not referenced. The `summary` is a derived view stored for convenience;
the canonical source of truth is `devices`.
"""
from __future__ import annotations

import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from configguard import __version__


# Snapshot contract: status values (per spec §7.2)
VALID_STATUSES = {"COMPLIANT", "NON-COMPLIANT", "ERROR"}

# Snapshot contract: level values (per spec §3.4)
VALID_LEVELS = {"LOW", "MEDIUM", "HIGH", "CRITICAL"}

# Current contract version
SNAPSHOT_VERSION = 1


class SnapshotValidationError(ValueError):
    """Raised when a dict fails Snapshot v1 schema validation."""


@dataclass
class DeviceSnapshot:
    """One device's record in a Snapshot.

    `device_name` is the device's **identity** (match key for cross-snapshot
    diff). `config_path` is **metadata** (where the file was found). Do not
    use `config_path` as a match key — paths may change between snapshots.
    """
    device_name: str
    config_path: str
    config_hash: str  # SHA-256 hex, lowercase, 64 chars, no prefix
    status: str  # COMPLIANT | NON_COMPLIANT | ERROR
    level: str  # LOW | MEDIUM | HIGH | CRITICAL
    severity_breakdown: dict
    findings: list = field(default_factory=list)
    error: Optional[str] = None

    def __post_init__(self):
        if self.status not in VALID_STATUSES:
            raise SnapshotValidationError(
                f"DeviceSnapshot.status must be one of {VALID_STATUSES}, got {self.status!r}"
            )
        if self.level not in VALID_LEVELS:
            raise SnapshotValidationError(
                f"DeviceSnapshot.level must be one of {VALID_LEVELS}, got {self.level!r}"
            )

    def to_dict(self) -> dict:
        return {
            "device_name": self.device_name,
            "config_path": self.config_path,
            "config_hash": self.config_hash,
            "status": self.status,
            "level": self.level,
            "severity_breakdown": self.severity_breakdown,
            "findings": [_f_to_dict(f) for f in self.findings],
            "error": self.error,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "DeviceSnapshot":
        if not isinstance(data, dict):
            raise SnapshotValidationError(f"DeviceSnapshot must be a dict, got {type(data)}")
        for required in ("device_name", "config_path", "config_hash", "status", "level",
                         "severity_breakdown", "findings", "error"):
            if required not in data:
                raise SnapshotValidationError(f"DeviceSnapshot missing required field: {required!r}")
        return cls(
            device_name=data["device_name"],
            config_path=data["config_path"],
            config_hash=data["config_hash"],
            status=data["status"],
            level=data["level"],
            severity_breakdown=data["severity_breakdown"],
            findings=[_f_from_dict(f) for f in data["findings"]],
            error=data["error"],
        )


@dataclass
class FleetSummary:
    """Derived view of `Snapshot.devices`. Stored in the file for convenience
    but can be regenerated by walking `devices` (see `from_devices`).

    `summary` is documented as derived. The canonical source of truth is
    `Snapshot.devices`.
    """
    device_count: int
    compliant: int
    non_compliant: int
    errored: int
    findings_total: int
    findings_failed: int
    findings_passed: int
    high_risk_device_count: int

    def to_dict(self) -> dict:
        return {
            "device_count": self.device_count,
            "compliant": self.compliant,
            "non_compliant": self.non_compliant,
            "errored": self.errored,
            "findings_total": self.findings_total,
            "findings_failed": self.findings_failed,
            "findings_passed": self.findings_passed,
            "high_risk_device_count": self.high_risk_device_count,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "FleetSummary":
        for required in ("device_count", "compliant", "non_compliant", "errored",
                         "findings_total", "findings_failed", "findings_passed",
                         "high_risk_device_count"):
            if required not in data:
                raise SnapshotValidationError(f"FleetSummary missing required field: {required!r}")
        return cls(**data)

    @classmethod
    def from_devices(cls, devices: list[DeviceSnapshot]) -> "FleetSummary":
        """Compute the summary from a list of DeviceSnapshots. This is the
        documented regeneration path; if a Snapshot's `summary` ever drifts
        from `devices`, this method produces the corrected value.
        """
        compliant = sum(1 for d in devices if d.status == "COMPLIANT")
        non_compliant = sum(1 for d in devices if d.status == "NON-COMPLIANT")
        errored = sum(1 for d in devices if d.status == "ERROR")
        findings_total = sum(len(d.findings) for d in devices)
        findings_failed = sum(
            sum(1 for f in d.findings if _finding_status(f) == "FAIL")
            for d in devices
        )
        findings_passed = sum(
            sum(1 for f in d.findings if _finding_status(f) == "PASS")
            for d in devices
        )
        high_risk_device_count = sum(
            1 for d in devices if d.level in ("HIGH", "CRITICAL")
        )
        return cls(
            device_count=len(devices),
            compliant=compliant,
            non_compliant=non_compliant,
            errored=errored,
            findings_total=findings_total,
            findings_failed=findings_failed,
            findings_passed=findings_passed,
            high_risk_device_count=high_risk_device_count,
        )


@dataclass
class Snapshot:
    """A Snapshot is the canonical artifact of `configguard fleet audit`.

    See `docs/superpowers/specs/2026-06-02-configguard-fleet-mode-design.md`
    for the v1 contract.
    """
    snapshot_version: int
    generator: dict
    generated_at: str
    source: dict
    summary: FleetSummary
    devices: list[DeviceSnapshot] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "snapshot_version": self.snapshot_version,
            "generator": self.generator,
            "generated_at": self.generated_at,
            "source": self.source,
            "summary": self.summary.to_dict(),
            "devices": [d.to_dict() for d in self.devices],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Snapshot":
        for required in ("snapshot_version", "generator", "generated_at",
                         "source", "summary", "devices"):
            if required not in data:
                raise SnapshotValidationError(f"Snapshot missing required field: {required!r}")
        if data["snapshot_version"] != SNAPSHOT_VERSION:
            raise SnapshotValidationError(
                f"Snapshot version {data['snapshot_version']!r} not supported "
                f"(this build only reads version {SNAPSHOT_VERSION})"
            )
        return cls(
            snapshot_version=data["snapshot_version"],
            generator=data["generator"],
            generated_at=data["generated_at"],
            source=data["source"],
            summary=FleetSummary.from_dict(data["summary"]),
            devices=[DeviceSnapshot.from_dict(d) for d in data["devices"]],
        )

    def write_json(self, path) -> None:
        """Write Snapshot to disk as pretty-printed JSON."""
        from pathlib import Path
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2))

    @classmethod
    def read_json(cls, path) -> "Snapshot":
        """Read a Snapshot from disk."""
        from pathlib import Path
        path = Path(path)
        return cls.from_dict(json.loads(path.read_text()))


# ---- helpers (Finding <-> dict, mirrors the per-device report shape) ----

def _f_to_dict(f) -> dict:
    """Convert a Finding to a dict matching the v0.1 per-device report shape."""
    return {
        "rule_id": f.rule_id,
        "rule_name": f.rule_name,
        "category": f.category,
        "severity": f.severity.value,
        "status": f.status.value,
        "evidence": f.evidence,
        "block_type": f.block_type,
        "block_name": f.block_name,
        "remediation": f.remediation,
        "evidence_summary": f.evidence_summary,
        "references": f.references,
    }


def _f_from_dict(data: dict) -> "Finding":
    """Reverse of _f_to_dict. Lazy import to avoid circular dependency."""
    from configguard.models import Finding, Severity, FindingStatus
    return Finding(
        rule_id=data["rule_id"],
        rule_name=data["rule_name"],
        category=data["category"],
        severity=Severity(data["severity"]),
        status=FindingStatus(data["status"]),
        evidence=data["evidence"],
        block_type=data.get("block_type"),
        block_name=data.get("block_name"),
        remediation=data.get("remediation"),
        evidence_summary=data.get("evidence_summary"),
        references=data.get("references") or [],
    )


def _finding_status(f) -> str:
    """Return the status string for a Finding (handles both enum and string)."""
    s = f.status
    return s.value if hasattr(s, "value") else str(s)


def make_generator_metadata(configguard_version: str | None = None) -> dict:
    """Build the `generator` block for a new Snapshot.

    `configguard_version` defaults to the current package `__version__`. Callers
    that want to record a different version (e.g., a future v0.5 build while the
    package is still tagged v0.2.0) can pass it explicitly.
    """
    return {
        "configguard_version": configguard_version or __version__,
        "python_version": f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}",
    }


def now_iso_utc() -> str:
    """Return current UTC time as ISO 8601 string with 'Z' suffix."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
